name: CI Build

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    name: Build & Publish
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/dotnet-build

      - name: Publish Self-Contained Executable
        run: dotnet publish src/ProcSim/ProcSim.csproj --configuration Release --output ./published --self-contained true -p:PublishSingleFile=true -p:TrimUnusedDependencies=true

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ProcSim-Build
          path: ./published
