name: CI Build

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build_and_publish:
    name: Build & Publish
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore ProcSim.sln

      - name: Build solution
        run: dotnet build ProcSim.sln --no-restore --configuration Release

      - name: Publish Self-Contained Executable
        run: dotnet publish src/ProcSim/ProcSim.csproj --configuration Release --output ./published --self-contained true -p:PublishSingleFile=true -p:TrimUnusedDependencies=true

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ProcSim-Build
          path: ./published
