name: PR Build Validation

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate_build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/dotnet-build
