name: Release

on:
  release:
    types: [published]

jobs:
  build_and_release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from tag
        id: version
        run: |
          $tag = "${{ github.event.release.tag_name }}"
          $version = $tag.TrimStart('v')
          echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Build
        uses: ./.github/actions/dotnet-build

      - name: Publish Self-Contained Executable
        run: >
          dotnet publish src/ProcSim/ProcSim.csproj
          --configuration Release
          --output ./published
          --self-contained true
          -p:PublishSingleFile=true
          -p:TrimUnusedDependencies=true
          -p:DebugType=None
          -p:DebugSymbols=false

      - name: Zip Release Artifact
        run: Compress-Archive -Path ./published/* -DestinationPath ProcSim-${{ steps.version.outputs.version }}.zip

      - name: Upload artifact to release
        uses: softprops/action-gh-release@v2
        with:
          files: ProcSim-${{ steps.version.outputs.version }}.zip
          fail_on_unmatched_files: true
